### ISSUE TITLE
Evaluation script for Task C?

### ISSUE THREAD

**Issue by sean0042** [abachaa/MEDIQA-Chat-2023#1]
Hi. 
Is there evaluation script for task C?
Thanks

**Comment by sean0042** [comment]
Another issue is that when i run divide_and_output_files.py , 
source file for task B and C are the same.

**Comment by abachaa** [comment]
Hi, Yes, the datasets for tasks B and C are the same (to maximize the amount of training data for each task, but the objectives are different).  
Similarly to tasks A and B, the evaluation of task C will rely on ensemble metrics that combine ROUGE, BLEURT, BERTScore, and other metrics.
