### ISSUE TITLE
Can we assume venv is installed?

### ISSUE THREAD

**Issue by JohnGiorgi** [abachaa/MEDIQA-Chat-2023#2]
For the `install.sh` script we need to write for submission, is it safe to assume [`venv`](https://docs.python.org/3/library/venv.html) will be installed and ready to use?

**Comment by wyim** [comment]
Yes, venv can be assumed to be installed.

**Comment by JohnGiorgi** [comment]
Thanks!

**Comment by JohnGiorgi** [comment]
@wyim As a follow-up question, which versions of python can we assume are installed?

**Comment by wyim** [comment]
Hi @JohnGiorgi,
Please assume python 3.8 is there to start with if you're using venv; then you can install another exact version if you need it. Thanks!

**Comment by JohnGiorgi** [comment]
Thank you!!
