### ISSUE TITLE
Issue running evaluate_summarization.py for "taskA"

### ISSUE THREAD

**Issue by JohnGiorgi** [abachaa/MEDIQA-Chat-2023#3]
I am having an issue running the `evaluate_summarization.py` script when `--task` is `"taskA"`. The traceback is:

```Traceback (most recent call last):
  File "/project/6061845/johnmg/MEDIQA-Chat-2023/./scripts/evaluate_summarization.py", line 221, in <module>
    df_shortsrc = full_df[full_df['src_len'] <= args.note_length_cutoff]
  File "/home/johnmg/mediqa-eval/lib/python3.10/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/johnmg/mediqa-eval/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'src_len'
```

It looks like this is because, at some point the script tries to access `src_len` in `full_df`:

https://github.com/abachaa/MEDIQA-Chat-2023/blob/dd40370e2c2e09fef9d121fee66e263a230dbf4c/scripts/evaluate_summarization.py#L220

However, this key is added by `add_section_divisions`, which is only called when `--task` is `"taskB"`:

https://github.com/abachaa/MEDIQA-Chat-2023/blob/dd40370e2c2e09fef9d121fee66e263a230dbf4c/scripts/evaluate_summarization.py#L147-L148

I think the possible fix is to move the entire block under an if statement (`if args.task == 'taskB'`):

https://github.com/abachaa/MEDIQA-Chat-2023/blob/dd40370e2c2e09fef9d121fee66e263a230dbf4c/scripts/evaluate_summarization.py#L219-L228

Does that sound right? Happy to make a PR if so!

(I know the challenge task is over, but we are hoping to use this script to generate scores on the validation script for our paper)

**Comment by wyim** [comment]
Hi @JohnGiorgi  -
Yes, this is correct, we had to do that change when we were evaluating!
Thanks for bringing this to our attention. Good point, pushed our latest fixes!

**Comment by abachaa** [comment]
Updated evaluate_summarization.py with the latest version used in the official evaluation.
